name: Automated tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.3
        with:
          node-version: 18
          cache: yarn

      - name: Verify build
        run: |
          yarn install
          yarn build
        env:
          RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}

      - name: Verify cosmos build
        run: |
          yarn build:cosmos
