name: Automated tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2.4.1
      with:
        node-version: '12.x'
    - name: Verify build
      run: |
        yarn install
        yarn build
      env:
        RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}
